name: flutter_koin
description: "Koin-like DI with code generation"
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  build: 4.0.4
  source_gen: 4.1.2
  analyzer: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: 2.12.2